
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk 
from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = tk.Tk()

home = Frame(window)
GenerateRpy = Frame(window)

home.grid(row=0,column=0)
GenerateRpy.grid(row=0,column=0)



window.geometry("369x485")
window.configure(bg="#262626")


canvas = Canvas(
    window,
    bg="#262626",
    height=485,
    width=369,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)

button_image_1 = PhotoImage(
    master=home,
    file=relative_to_assets("ge.png"))
button_1 = Button(
    master=home,
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=15.0,
    y=105.56097412109375,
    width=338.0,
    height=41.26829528808594
)

button_image_2 = PhotoImage(
    master=home,
    file=relative_to_assets("gr.png"))
button_2 = Button(
    master=home,
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: GenerateRpy.tkraise(),
    relief="flat"
)
button_2.place(
    x=15.0,
    y=156.0,
    width=338.0,
    height=41.26829528808594
)

button_image_3 = PhotoImage(
    master=home,
    file=relative_to_assets("update.png"))
button_3 = Button(
    image=button_image_3,
    master=home,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=15.0,
    y=206.43902587890625,
    width=338.0,
    height=41.26829528808594
)

button_image_4 = PhotoImage(
    master=home,
    file=relative_to_assets("donate.png"))
button_4 = Button(
    master=home,
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=15.0,
    y=339.4146423339844,
    width=338.0,
    height=41.26829147338867
)

button_image_5 = PhotoImage(
    master=home,
    file=relative_to_assets("close.png"))
button_5 = Button(
    master=home,
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=15.0,
    y=397.8780517578125,
    width=338.0,
    height=41.26829528808594
)

canvas.create_text(
    166.0,
    461.0,
    anchor="nw",
    text="V1.0.7",
    fill="#FFFFFF",
    font=("Inter Medium", 12 * -1)
)

image_image_1 = PhotoImage(
    master=home,
    file=relative_to_assets("logo_home.png"))
image_1 = canvas.create_image(
    184.0,
    46.0,
    image=image_image_1
)

###

Generate_image = PhotoImage(
 
    file=relative_to_assets("generate.png"))
Generate = Button(
    image=Generate_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: home.tkraise(),
    relief="flat"
)
Generate.place(
    x=15.0,
    y=397.8780517578125,
    width=338.0,
    height=41.26829528808594
)


logoRpy_image = PhotoImage(
     
    file=relative_to_assets("rpygenerate.png"))
logoRpy = canvas.create_image(
    184.0,
    46.0,
    image=logoRpy_image
)

Input_image = PhotoImage(
    
    file=relative_to_assets("input.png"))
Input = canvas.create_image(
    185.5,
    144.5,
    image=Input_image
)
entry_1 = Entry(
    master=GenerateRpy,
    bd=0,
    bg="#201E1E",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=43.0,
    y=128.0,
    width=285.0,
    height=31.0
)

canvas.create_text(
    38.0,
    107.0,
    anchor="nw",
    text="Language",
    fill="#FFFFFF",
    font=("Inter SemiBold", 15 * -1)
)



home.tkraise()
window.resizable(False, False)
window.mainloop()
